
/* Drop Tables */

DROP TABLE test_write CASCADE CONSTRAINTS;




/* Create Tables */

CREATE TABLE test_write
(
	wr_subject varchar2(100) NOT NULL,
	wr_content varchar2(100),
	wr_name varchar2(100) NOT NULL,
	wr_viewcnt number NOT NULL,
	wr_regdate date NOT NULL
);
SELECT * FROM TEST_WRITE;
SELECT * FROM ORDER_TB ;

INSERT INTO ORDER_TB VALUES(1,SYSDATE,30000,1);
INSERT INTO ORDER_TB VALUES(2,SYSDATE,50000,1);
INSERT INTO ORDER_TB VALUES(3,SYSDATE,70000,1);
INSERT INTO ORDER_TB VALUES(8,SYSDATE,70000,2);
INSERT INTO ORDER_TB VALUES(9,SYSDATE,70000,2);
INSERT INTO ORDER_TB VALUES(4,to_date('20-06-03'),4000,1);
INSERT INTO ORDER_TB VALUES(5,to_date('20-06-03'),60000,1);
INSERT INTO ORDER_TB VALUES(6,to_date('20-06-03'),80000,2);
INSERT INTO ORDER_TB VALUES(7,to_date('20-06-03'),90000,2);

SELECT VALUE FROM NLS_SESSION_PARAMETERS WHERE PARAMETER = 'NLS_DATE_FORMAT';



/*일별 합산 구하기*/
SELECT
STORE_UID ,
TO_CHAR(TO_DATE (order_regdate,'yyyy-mm-dd'),'yy-mm-dd'),
SUM(order_totalprice)
FROM ORDER_TB 
GROUP BY TO_CHAR(TO_DATE (order_regdate,'yyyy-mm-dd'),'yy-mm-dd'), STORE_UID ;

SELECT SUM(ORDER_TOTALPRICE ) FROM ORDER_TB GROUP BY STORE_UID ;

